#!/bin/bash

if [ ! -d "$HOME/bin" ]; then
    mkdir $HOME/bin
    echo "bin" >> $HOME/.hidden
fi

SRC_DIR=$(cd $(dirname $0) && pwd)
DEST_DIR="$HOME/bin"

cp -ur ${SRC_DIR}/ipearthwallpaper ${DEST_DIR}

tmp=${TMPDIR:-/tmp}/xyz.$$

trap "rm -f $tmp; exit 1" 0 1 2 3 13 15
crontab -l | sed '/ipearthwallpaper/d' > $tmp  # Capture crontab; delete old entry
echo "0,20,40 * * * * $HOME/bin/ipearthwallpaper" >> $tmp
crontab < $tmp
rm -f $tmp
trap 0